// LinkChat/client/src/pages/Register.jsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { authApi } from '../utils/api'
import { useAuthStore } from '../store/authStore'
import { useToast } from '../components/Toast'

const Register = () => {
  const [phone, setPhone] = useState('')
  const [code, setCode] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [codeLoading, setCodeLoading] = useState(false)
  const [countdown, setCountdown] = useState(0)
  
  const navigate = useNavigate()
  const login = useAuthStore((state) => state.login)
  const { showToast, ToastComponent } = useToast()

  const handleSendCode = async () => {
    if (!/^1[3-9]\d{9}$/.test(phone)) {
      showToast('请输入正确的手机号', 'error')
      return
    }

    setCodeLoading(true)
    try {
      await authApi.sendCode(phone, 'register')
      showToast('验证码发送成功')
      setCountdown(60)
      const timer = setInterval(() => {
        setCountdown(prev => {
          if (prev <= 1) {
            clearInterval(timer)
            return 0
          }
          return prev - 1
        })
      }, 1000)
    } catch (error) {
      showToast(error.response?.data?.message || '发送失败', 'error')
    } finally {
      setCodeLoading(false)
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    
    if (!/^1[3-9]\d{9}$/.test(phone)) {
      showToast('请输入正确的手机号', 'error')
      return
    }
    
    if (!code) {
      showToast('请输入验证码', 'error')
      return
    }
    
    if (!password || password.length < 6) {
      showToast('密码长度不能少于6位', 'error')
      return
    }
    
    if (password !== confirmPassword) {
      showToast('两次输入的密码不一致', 'error')
      return
    }

    setLoading(true)
    try {
      const response = await authApi.register({
        phone,
        code,
        password
      })
      
      login(response.data.user, response.data.token)
      showToast('注册成功')
      navigate('/')
    } catch (error) {
      showToast(error.response?.data?.message || '注册失败', 'error')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px'
    }}>
      {ToastComponent}
      <div className="card" style={{ width: '100%', maxWidth: '420px' }}>
        <div className="text-center" style={{ marginBottom: '32px' }}>
          <h1 style={{ 
            fontSize: '32px', 
            fontWeight: '700',
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            marginBottom: '8px'
          }}>注册账号</h1>
          <p style={{ color: '#666', fontSize: '14px' }}>加入乐聊，开启快乐聊天</p>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label className="form-label">手机号</label>
            <input
              type="tel"
              className="form-input"
              placeholder="请输入手机号"
              value={phone}
              onChange={(e) => setPhone(e.target.value.replace(/\D/g, ''))}
              maxLength={11}
            />
          </div>

          <div className="form-group">
            <label className="form-label">验证码</label>
            <div className="code-input-group">
              <input
                type="text"
                className="form-input"
                placeholder="请输入验证码"
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
                maxLength={6}
              />
              <button
                type="button"
                className="code-btn"
                onClick={handleSendCode}
                disabled={countdown > 0 || codeLoading}
              >
                {codeLoading ? '发送中...' : countdown > 0 ? `${countdown}s` : '获取验证码'}
              </button>
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">设置密码</label>
            <input
              type="password"
              className="form-input"
              placeholder="请设置6-20位密码"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              maxLength={20}
            />
          </div>

          <div className="form-group">
            <label className="form-label">确认密码</label>
            <input
              type="password"
              className="form-input"
              placeholder="请再次输入密码"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              maxLength={20}
            />
          </div>

          <button 
            type="submit" 
            className="btn btn-primary"
            disabled={loading}
            style={{ marginBottom: '16px' }}
          >
            {loading ? <span className="loading"></span> : '注册'}
          </button>
        </form>

        <div className="text-center">
          <span style={{ color: '#666', fontSize: '14px' }}>已有账号？</span>
          <Link to="/login" className="link" style={{ marginLeft: '4px' }}>立即登录</Link>
        </div>
      </div>
    </div>
  )
}

export default Register

// QuickRide/frontend/src/views/auth/Register.vue
<template>
  <div class="register-container">
    <div class="register-card">
      <div class="logo-section">
        <el-icon :size="48" color="#667eea"><Van /></el-icon>
        <h1>注册账号</h1>
        <p>加入捷行出行，开启便捷之旅</p>
      </div>

      <el-form :model="form" class="register-form">
        <el-form-item>
          <el-input
            v-model="form.phone"
            placeholder="请输入手机号"
            maxlength="11"
            :prefix-icon="Phone"
          />
        </el-form-item>
        <el-form-item>
          <el-input
            v-model="form.code"
            placeholder="请输入验证码"
            maxlength="4"
            :prefix-icon="Key"
          >
            <template #append>
              <el-button
                :disabled="countdown > 0 || !isValidPhone"
                @click="sendCode"
              >
                {{ countdown > 0 ? `${countdown}s` : '获取验证码' }}
              </el-button>
            </template>
          </el-input>
        </el-form-item>
        <el-form-item>
          <el-input
            v-model="form.nickname"
            placeholder="请输入昵称（选填）"
            :prefix-icon="User"
          />
        </el-form-item>
        <el-form-item>
          <el-input
            v-model="form.password"
            type="password"
            placeholder="请设置密码（选填）"
            show-password
            :prefix-icon="Lock"
          />
        </el-form-item>
        <el-form-item>
          <el-button
            type="primary"
            class="register-btn"
            :loading="loading"
            @click="handleRegister"
          >
            立即注册
          </el-button>
        </el-form-item>
      </el-form>

      <div class="register-footer">
        <span>已有账号？</span>
        <router-link to="/login">去登录</router-link>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { Phone, Key, Lock, User, Van } from '@element-plus/icons-vue';
import { useUserStore } from '@/stores/user';
import api from '@/utils/api';

const router = useRouter();
const userStore = useUserStore();

const loading = ref(false);
const countdown = ref(0);

const form = ref({
  phone: '',
  code: '',
  nickname: '',
  password: ''
});

const isValidPhone = computed(() => /^1[3-9]\d{9}$/.test(form.value.phone));

function sendCode() {
  if (!isValidPhone.value) {
    ElMessage.warning('请输入有效的手机号');
    return;
  }

  api.post('/auth/send-code', { phone: form.value.phone, type: 'register' })
    .then(() => {
      ElMessage.success('验证码已发送');
      startCountdown();
    });
}

function startCountdown() {
  countdown.value = 60;
  const timer = setInterval(() => {
    countdown.value--;
    if (countdown.value <= 0) {
      clearInterval(timer);
    }
  }, 1000);
}

function handleRegister() {
  if (!form.value.phone || !form.value.code) {
    ElMessage.warning('请填写必填信息');
    return;
  }

  loading.value = true;
  api.post('/auth/register', form.value)
    .then((res) => {
      userStore.setToken(res.data.token);
      userStore.setUserInfo(res.data.user);
      ElMessage.success('注册成功');
      router.push('/home');
    })
    .finally(() => {
      loading.value = false;
    });
}
</script>

<style scoped>
.register-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 20px;
}

.register-card {
  background: white;
  border-radius: 16px;
  padding: 40px;
  width: 100%;
  max-width: 420px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);
}

.logo-section {
  text-align: center;
  margin-bottom: 30px;
}

.logo-section h1 {
  font-size: 24px;
  margin: 10px 0 5px;
  color: #333;
}

.logo-section p {
  color: #999;
  font-size: 14px;
}

.register-btn {
  width: 100%;
  height: 44px;
  font-size: 16px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border: none;
}

.register-btn:hover {
  opacity: 0.9;
}

.register-footer {
  text-align: center;
  margin-top: 20px;
  font-size: 14px;
  color: #666;
}

.register-footer a {
  color: #667eea;
  text-decoration: none;
  margin-left: 5px;
}

.register-footer a:hover {
  text-decoration: underline;
}
</style>
